/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/pages/**/*.{js,jsx}", "./src/components/**/*.{js,jsx}"],
  safelist: [
    "text-r3xl",
    "text-r5xl",
    "text-orange",
    "text-blue",
    "text-white",
    "bg-darkgrey",
    "bg-orange",
    "p-6",
    "p-4",
    "mb-0",
    "w-1/2",
    "w-1/3",
    "w-4/5",
    "items-end",
    "items-center",
    "justify-center",
    "justify-end",
    "flex",
    "h-full",
    "fill-orange",
    "fill-white",
    "stroke-black",
    "stroke",
    "stroke-2",
    "mx-auto",
    "max-w-2xl",
    "py-16",
    "px-4",
    "text-center",
    "sm:py-20",
    "sm:px-6",
    "lg:px-8",
    "grid",
    "place-items-center",
  ],
  theme: {
    extend: {
      screens: {
        md: "801px",
        xl: "1367px",
      },
      fontSize: {
        rxs: "calc(var(--scale) * 0.75rem)",
        rsm: "calc(var(--scale) * 0.875rem)",
        rbase: "calc(var(--scale) * 1rem)",
        rlg: "calc(var(--scale) * 1.125rem)",
        rxl: "calc(var(--scale) * 1.25rem)",
        r2xl: "calc(var(--scale) * 1.5rem)",
        r3xl: "calc(var(--scale) * 1.875rem)",
        r4xl: "calc(var(--scale) * 2.25rem)",
        r5xl: "calc(var(--scale) * 3rem)",
        r6xl: "calc(var(--scale) * 3.75rem)",
        r7xl: "calc(var(--scale) * 4.5rem)",
        r8xl: "calc(var(--scale) * 6rem)",
        r9xl: "calc(var(--scale) * 8rem)",
      },
      zIndex: {
        70010: "70010", // impressions
        70020: "70020",
        70030: "70030",
        80010: "80010", // context
        80020: "80020",
        80030: "80030",
        90000: "90000", // for beliefs widget
      },
      colors: {
        white: "#fcfcfc",
        allwhite: "#ffffff",
        lightgrey: "#a7b1b7",
        blue: "#293f58",
        green: "#c8df8c",
        orange: "#f58333",
        darkgrey: "#393d34",
        black: "#10120d",
        allblack: "#000000",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
