/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,jsx,tsx}",
    "./src/components/**/*.{js,jsx,tsx}",
    "./src/shopify-components/**/*.{js,jsx,tsx}",
    "./src/templates/**/*.{js,jsx,tsx}",
  ],
  safelist: [
    "motion-safe:animate-fadeInUp",
    "motion-safe:animate-fadeIn",
    "align-bottom",
    "before:align-bottom",
    "block",
    "bg-darkgrey",
    "bg-lightgrey",
    "bg-green",
    "bg-teal-400",
    "bg-sky-400",
    "bg-indigo-400",
    "bg-purple-400",
    "bg-pink-400",
    "bg-red-400",
    "bg-transparent",
    "fill-orange",
    "fill-white",
    "fill-darkgrey",
    "fill-slate-50",
    "fill-slate-100",
    "fill-slate-200",
    "flex",
    "flex-col",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-inset",
    "focus:ring-orange",
    "focus-visible:outline",
    "focus-visible:outline-2",
    "focus-visible:outline-orange",
    "font-bold",
    "font-semibold",
    "font-action",
    "h-full",
    "hover:bg-gray-100",
    "hover:text-gray-500",
    "hover:text-orange",
    "hover:text-allwhite",
    "hover:underline",
    "hover:bg-allwhite",
    "hover:bg-allblack",
    "hover:text-blue",
    "hover:text-white",
    "inline-block",
    "inline-flex",
    "items-center",
    "items-end",
    "justify-center",
    "justify-end",
    "leading-7",
    "leading-8",
    "leading-10",
    "leading-12",
    "lg:max-w-5xl",
    "lg:px-12",
    "lg:px-8",
    "max-w-sm",
    "max-w-md",
    "max-w-lg",
    "max-w-xl",
    "max-w-2xl",
    "max-w-7xl",
    "md:flex",
    "md:flex-row",
    "md:pt-24",
    "md:pb-48",
    "mb-6",
    "ml-6",
    "mt-6",
    "mt-9",
    "mt-10",
    "mt-48",
    "mx-6",
    "mx-auto",
    "my-9",
    "my-16",
    "my-32",
    "my-auto",
    "no-underline",
    "p-4",
    "p-6",
    "pb-48",
    "pb-54",
    "pl-12",
    "pr-6",
    "pr-12",
    "pt-16",
    "pt-24",
    "pt-32",
    "px-3.5",
    "px-4",
    "py-1.5",
    "py-2",
    "py-8",
    "py-16",
    "py-24",
    "py-[40%]",
    "relative",
    "rounded-md",
    "text-r2xl",
    "shadow-sm",
    "sm:px-6",
    "sm:px-8",
    "sm:py-20",
    "sm:text-2xl",
    "sm:text-4xl",
    "sm:text-5xl",
    "stroke",
    "stroke-2",
    "stroke-black",
    "text-3xl",
    "text-4xl",
    "text-base",
    "text-black",
    "text-blue",
    "text-center",
    "text-darkgrey",
    "text-green",
    "text-gray-400",
    "text-gray-600",
    "text-gray-800",
    "text-gray-900",
    "text-orange",
    "text-offwhite",
    "text-r3xl",
    "text-r5xl",
    "text-lg",
    "text-rlg",
    "text-rbase",
    "text-xl",
    "text-rxl",
    "tracking-tight",
    "underline",
    "underline-offset-1",
    "w-1/2",
    "w-2/3",
    "w-3/5",
    "w-4/5",
    "w-[110%]",
  ],
  theme: {
    extend: {
      animation: {
        fadeIn: "fadeIn 1s ease-in",
        fadeInUp: "fadeInUp 1s ease-in",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeInUp: {
          "0%": { transform: "translate3d(0, 10px, 0)", opacity: "0" },
          "100%": { transform: "translate3d(0, 0, 0)", opacity: "1" },
        },
      },
      lineHeight: {
        12: "3rem",
      },
      screens: {
        md: "801px",
        xl: "1367px",
      },
      fontFamily: {
        action: ["Organetto-Regular"],
      },
      fontSize: {
        rxs: "calc(var(--scale) * 0.75rem)",
        rsm: "calc(var(--scale) * 0.875rem)",
        rbase: "calc(var(--scale) * 1rem)",
        rlg: "calc(var(--scale) * 1.125rem)",
        rxl: "calc(var(--scale) * 1.25rem)",
        r2xl: "calc(var(--scale) * 1.5rem)",
        r3xl: "calc(var(--scale) * 1.875rem)",
        r4xl: "calc(var(--scale) * 2.25rem)",
        r5xl: "calc(var(--scale) * 3rem)",
        r6xl: "calc(var(--scale) * 3.75rem)",
        r7xl: "calc(var(--scale) * 4.5rem)",
        r8xl: "calc(var(--scale) * 6rem)",
        r9xl: "calc(var(--scale) * 8rem)",
      },
      zIndex: {
        70010: "70010", // impressions
        70020: "70020",
        70030: "70030",
        80000: "80000", // for footer
        80010: "80010", // context
        80020: "80020",
        80030: "80030",
        90000: "90000", // for beliefs widget
      },
      colors: {
        white: "#fcfcfc",
        offwhite: "#e3e3e3",
        allwhite: "#ffffff",
        lightgrey: "#a7b1b7",
        blue: "#293f58",
        green: "#c8df8c",
        orange: "#f58333",
        darkgrey: "#393d34",
        black: "#10120d",
        allblack: "#000000",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
